version: "3.8"
services:
  backend:    # DAI: backend   USDC: backend2  ETH: backend3
    build: . # Build image from local Dockerfile
    command: bash -c 'npm start'
    expose:
      - "3000"
    depends_on:
      - redis
    restart: always
    networks:
      - app-network

  redis:    # DAI: redis   USDC: redis2    ETH: redis3
    image: redis
    restart: always
    privileged: true
    expose:
      - "6379"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    volumes:
      - ${REDIS_PATH}/data:/data:rw
      - ${REDIS_PATH}/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /usr/local/cert/__orbiter_finance.crt:/etc/nginx/certs/__orbiter_finance.crt
      - ./log:/var/log/nginx
      - /usr/local/cert/private.key:/etc/nginx/certs/private.key
    ports:
      - 3000:3000   # DAI: 3000   USDC: 3001    ETH: 3002
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
